### PR TITLE
Output DataFrames.DataFrame and add rcParams

### PR DESCRIPTION
**Pull request by sethaxen**
Fixes https://github.com/arviz-devs/ArviZ.jl/issues/34

### CODE REVIEW

**Comment by ahartikainen** [comment]
Was there something holding back for this PR?

**Comment by sethaxen** [comment]
Mainly revisiting the missed conversions documented in https://github.com/arviz-devs/ArviZ.jl/issues/34#issuecomment-561127309 and figuring out a fix either in this package or somewhere else.

The priority of this dropped somewhat as Pandas.jl was updated to be compatible with the latest pandas and to render nicely in Jupyter notebooks and HTML. They're still not great for the Julia ecosystem though, and I'd like to switch over still.

**Comment by ahartikainen** [comment]
I think we could normalize the dtypes in the summary dataframe on Python side. Would that work?

**Comment by sethaxen** [comment]
> I think we could normalize the dtypes in the summary dataframe on Python side. Would that work?

Perhaps, what do you mean by "normalize"?

**Comment by ahartikainen** [comment]
Change dtypes to their default versions?

int --> np.int64
float --> np.float64
bool --> bool (np.bool ?)

**Comment by sethaxen** [comment]
Oh, that could work. First, let me refresh this PR with the latest changes to ArviZ and see if the problem persists. Then we can try that.

**Comment by sethaxen** [comment]
I'm mid-refresh, but I can already see that the issue persists, so let's go ahead and move forward with normalization.

**Comment by sethaxen** [comment]
Even with the issue documented in #34, I think this is still an improvement over Pandas and will go ahead and merge this once I get more coverage.

**Pull request merged**
